name: Push Docker image into Amazon ECR

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - "Dockerfile"
      - ".github/workflows/push-ecr.yml"
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: ecs-threat-composer

jobs:
  Build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image uri
        run: echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t $IMAGE_URI .

      - name: Scan image to prevent vulnerability
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ env.IMAGE_URI }}
          exit-code: "1"
          severity: "CRITICAL,HIGH"

      - name: Push image
        run: |
          docker push $IMAGE_URI
          echo "Pushed $IMAGE_URI"