name: Push Docker image into Amazon ECR

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - "Dockerfile"
      - ".github/workflows/push-ecr.yml"
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type YES to run"
        required: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }} 
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY }} 

jobs:
  Build-and-push:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'YES')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: "arn:aws:iam::407933037834:role/gha-ecr-push"
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build docker image (latest)
        run: docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

      - name: Tag docker image (sha)
        run: docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      - name: Push docker image (latest)
        run: |
          IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY:latest"
          docker push "$IMAGE"
          echo "Pushed: $IMAGE"

      - name: Push docker image (sha)
        run: |
          IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}"
          docker push "$IMAGE"
          echo "Pushed: $IMAGE"